language: elixir
elixir:
  - '1.7.4'
otp_release:
  - '21.1'
node_js:
  - '10.13.0'

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - postgresql

env:
  global:
  - PGPORT=5433
  - MIX_ENV=test

before_script:
  - cp apps/ui/config/travis_test.exs apps/ui/config/test.exs
  - mix deps.get
  - cd apps/ui/assets && npm install && cd ..
  - mix do ecto.create, ecto.migrate

script:
  - mix test
