language: elixir
elixir:
  - '1.7.4'
otp_release:
  - '21.1'
node_js:
  - '10.13.0'

cache: apt

before_install:
  - sudo service postgresql stop
  - sudo apt-get -y -qq --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-contrib-$PGVERSION

env:
  global:
    - MIX_ENV=test
    - PGUSER=postgres
    - PG_SOCKET_DIR=/var/run/postgresql
    - PGVERSION=10

before_script:
  - echo "local all postgres trust" | sudo tee /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgres 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_md5_pw 127.0.0.1/32 md5" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_cleartext_pw 127.0.0.1/32 password" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - if [ `echo "$PGVERSION >= 10.0" | bc` -eq 1 ]; then echo "host all postgrex_scram_pw 127.0.0.1/32 scram-sha-256" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf; fi
  - sudo service postgresql restart
  - cp apps/ui/config/travis_test.exs apps/ui/config/test.exs
  - mix deps.get
  - cd apps/ui/assets && npm install && cd ..
  - psql -c 'create database commentable_test;' -U postgres
  - mix ecto.migrate

script:
  - mix test
